version: '3'
services:
  postfix:
    build:
      context: ./postfix
    container_name: postfix
    ports:
      - '25:25'
    depends_on:
      - db
    networks:
      - postfix_network
    volumes:
      - ./postfix/conf/main.cf:/etc/postfix/main.cf
      - ./postfix/conf/master.cf:/etc/postfix/master.cf
      - ./postfix/conf/transport:/etc/postfix/transport
      - ./postfix/conf/virtual:/etc/postfix/virtual
      - ./logs:/var/log/postfix
      - ./.env:/opt/app/.env
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:  
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postfix_network

  flask_app:
    build:
      context: ./flask_app
    container_name: flask_app
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./flask_app:/opt/app
      - ./logs:/logs
    networks:
      - postfix_network

networks:
  postfix_network:
    driver: bridge

volumes:
  my-db: